"""Add issued to Drop

Revision ID: 66c67370e6ab
Revises: 3900ca7c1d17
Create Date: 2025-04-24 13:55:43.011909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c67370e6ab'
down_revision = '3900ca7c1d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issued', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop', schema=None) as batch_op:
        batch_op.drop_column('issued')

    # ### end Alembic commands ###
